dirConfig:
  workingDir: "C:\\Users\\alaab\\OneDrive\\Desktop\\AberdeenProject"
  # workingDir: "/home/linux/Desktop/AberdeenProject"
  dataDir: "C:\\Users\\alaab\\OneDrive\\Desktop\\AberdeenProject\\data"
  # dataDir: "/home/linux/Desktop/AberdeenProject/data"
  pklDir: "C:\\Users\\alaab\\OneDrive\\Desktop\\AberdeenProject\\pickledData"
  # pklDir: "/home/linux/Desktop/AberdeenProject/pickledData"

fileConfig:
  pickledData_all: "dataframe_all.pkl"
  pickledData_kept: "dataframe_kept.pkl"

dataframeConfig:
  joinBasedOn: "SITEID"

missingConfig:
  threshold: 70

# missing value strategy: "mean", "median", "most_frequent", "constant", "custom"
# preprocessing: "onehot", None
features:
  ENT_LAPTOP: 
    missing: "most_frequent"
    preprocessing: "onehot"
  ENT_SERVER: 
    missing: "most_frequent"
    preprocessing: "onehot"
  WIRELESS_USERS: 
    missing: "most_frequent" 
    preprocessing: None
  LAPTOPS: 
    missing: "most_frequent" 
    preprocessing: None
labels:
  STORAGE_CAPACITY_EXPANSION_PLS:
    missing: "most_frequent" 
    preprocessing: None














  # ENT_PRINTER: "most_frequent"
  # ENT_STORAGE: "most_frequent"
  # ENT_EXTENSIONS: "most_frequent"
  # ENT_WIRELESS_USERS: "most_frequent"
  # ENT_INTERNET_USERS: "most_frequent"
  # ENT_NETWORKLINES: "most_frequent"
  # ENT_IT_BUDGET: "most_frequent"
  # ENT_HARDWARE_BUDGET: "most_frequent"
  # ENT_PC_BUDGET: "most_frequent"