dirConfig:
  workingDir: "D:\\OneDrive - bwedu\\Documents\\MASTER\\6.Semester_Ausland\\Aberdeen\\AberdeenProject\\AberdeenProject"
  # workingDir: "/home/linux/Desktop/AberdeenProject"
  dataDir: "D:\\OneDrive - bwedu\\Documents\\MASTER\\6.Semester_Ausland\\Aberdeen\\AberdeenProject\\AberdeenProject\\data"

  # dataDir: "/home/linux/Desktop/AberdeenProject/data"
  pklDir: "D:\\OneDrive - bwedu\\Documents\\MASTER\\6.Semester_Ausland\\Aberdeen\\AberdeenProject\\AberdeenProject\\pickeledData"
  # pklDir: "/home/linux/Desktop/AberdeenProject/pickledData"

fileConfig:
  pickledData_all: "dataframe_all.pkl"
  pickledData_afterThFiltering: "dataframe_kept.pkl"

dataframeConfig:
  joinBasedOn: "SITEID"

missingConfig:
  threshold: 70

features:
  EMPLE: 
    missing: "mean"
    preprocessing: None
  REVEN: 
    missing: "mean"
    preprocessing: None
  MOBILE_WORKERS: 
    missing: "mean" 
    preprocessing: None
  MOBILE_INTL:
    missing: "most_frequent" 
    preprocessing: "one_hot"
  DESKTOP_MANUF: 
    missing: "most_frequent" 
    preprocessing: "one_hot"
  LAPTOP_MANUF: 
    missing: "most_frequent" 
    preprocessing: "one_hot"
  IT_BUDGET: 
    missing: "mean" 
    preprocessing: None
  HARDWARE_BUDGET: 
    missing: "mean" 
    preprocessing: None
  PC_BUDGET: 
    missing: "mean" 
    preprocessing: None
  IT_STAFF: 
    missing: "most_frequent" 
    preprocessing: "one_hot"
  INTERNET_USERS: 
    missing: "most_frequent" 
    preprocessing: "one_hot"
  DEVELOPERS: 
    missing: "most_frequent" 
    preprocessing: "one_hot"
  PCS: 
    missing: "mean" 
    preprocessing: None
  DESKTOPS: 
    missing: "mean" 
    preprocessing: None
  LAPTOPS: 
    missing: "mean" 
    preprocessing: None
  MULTINATIONAL: 
    missing: "most_frequent" 
    preprocessing: "one_hot"
  ENT_TYPE: 
    missing: "most_frequent" 
    preprocessing: "one_hot"
  ENT_RANK: 
    missing: "mean" 
    preprocessing: None
  ENT_LAPTOP: 
    missing: "most_frequent" 
    preprocessing: "one_hot"
  
labels:
  LAPTOP_PLS:
    missing: "most_frequent" 
    preprocessing: None
