dirConfig:
  workingDir: "C:\\Users\\alaab\\OneDrive\\Desktop\\AberdeenProject\\AberdeenProject"
  # workingDir: "/home/linux/Desktop/AberdeenProject"
  dataDir: "C:\\Users\\alaab\\OneDrive\\Desktop\\AberdeenProject\\AberdeenProject\\data"
  # dataDir: "/home/linux/Desktop/AberdeenProject/data"
  pklDir: "C:\\Users\\alaab\\OneDrive\\Desktop\\AberdeenProject\\AberdeenProject\\pickledData"
  # pklDir: "/home/linux/Desktop/AberdeenProject/pickledData"

fileConfig:
  pickledData_all: "dataframe_all.pkl"
  pickledData_afterThFiltering: "dataframe_kept.pkl"

dataframeConfig:
  joinBasedOn: "SITEID"

missingConfig:
  threshold: 70

features:
  ENT_LAPTOP: 
    missing: "most_frequent"
    preprocessing: "onehot"
  ENT_SERVER: 
    missing: "most_frequent"
    preprocessing: "onehot"
  WIRELESS_USERS: 
    missing: "most_frequent" 
    preprocessing: None
  LAPTOPS: 
    missing: "most_frequent" 
    preprocessing: None

labels:
  STORAGE_CAPACITY_EXPANSION_PLS:
    missing: "most_frequent" 
    preprocessing: None
